dataset:
    dataset_name: 'coco'
    root: '<path to pickle files>'
    train_pickle: 'training_set_ltd_l.pickle'
    val_pickle: 'validation_set_ltd.pickle'
    test_pickle: 'test_set_ltd_l.pickle'
    vocab_file: 'coco_vocab.pkl'
    captions_per_image: 5

experiment:
    wandb_project: 'tmlr_experiments'
    experiment_name: 'coco_ltd_finetune'
    wandb_dir: '/output/coco/tmlr_experiments'
    out_dir:   '/output/coco/tmlr_experiments'
    cache_dir: '/output/wenb'

dataloader:
    batch_size: 128
    eval_batch_size: 8
    num_workers: 10
    crop_size: 224
    random_erasing_prob: 0.2
    caption_drop_prob: 0.1
    target_key: 'target-large'

model:
    name: ltd
    embed_dim: 1024
    caption_encoder:
        wemb_type: glove
        word_dim: 300
        tune_from_start: False
        txt_finetune: True
    image_encoder:
         img_finetune: False
         cnn_type: resnet50
         tune_from_start: False
    target_decoder:
        decode_target: False
        reconstruction_dim: 768
        hidden_features: 1024
        input_decoding: False
    vsrn:
        use_model: True
        embed_dim: 1024
        no_imgnorm: False
        image_encoder:
            img_dim: 2048 # dim of the precomputed features
        caption_encoder:
            word_dim: 300
            num_layers: 1

# optimizer configuration
optimizer:
    name: adamp
    learning_rate: 0.0002
    weight_decay: 0.0
    weight_averaging:
        use_weight_averaging: True
        checkpoints: 5
        percentage: 0.9

# lr scheduler configuration
lr_scheduler:
    name: multi_step_lr
    T_max: 30
    milestones: [15]

# criterion configuration
criterion:
    name: 'infonce'
    tau: 0.05
    margin: 0.2
    reconstruction_metric: 'cosine'

recconstruction_constraint:
    use_constraint: False
    alpha: 0.90
    bound:  0.2
    start_val: 1.
    max: 100.

# detailed training configuration
train:
    model_save_path: model_last.pth
    best_model_save_path: model_best.pth
    n_epochs: 30
    finetune_lr_decay: 0.1
    log_step: 10
    grad_clip: 2
    val_epochs: 1
    use_fp16: False